apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        nuage.io/subnet: operations-wf
        nuage.io/zone: operations-wf
        nuage.io/user: admin

    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

