---
- name: Create limits.conf directory
  file:
    dest: /etc/systemd/system/haproxy.service.d
    state: directory
    mode: 0660
    owner: root
    group: root
  changed_when: false

- name: Create limits.conf file
  file:
    dest: /etc/systemd/system/haproxy.service.d/limits.conf
    state: touch
    mode: 0660
    owner: root
    group: root
  changed_when: false

- name: Configure the nofile limits for haproxy
  ini_file:
    dest: /etc/systemd/system/haproxy.service.d/limits.conf
    section: Service
    option: LimitNOFILE
    value: "{{ loadbalancer_limit_nofile | default(100000) }}"
  notify: restart haproxy

- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  notify: restart haproxy

- name: Enable and start haproxy
  systemd:
    name: haproxy
    state: restarted
    enabled: yes
    daemon_reload: yes
  register: start_result

- include: iptables.yml

- set_fact:
    haproxy_start_result_changed: "{{ start_result | changed }}"

